###
# CUDA
###

cuda_groups: 8192
cuda_threads: 1024

###
# Colouring
###

colour_method: 4
colour_palette:
  - [0, 0, 0] # Points in set
  - [230, 0, 10]
  - [270, 60, 50]
  - [270, 60, 50]
  - [230, 80, 66]
  - [230, 80, 66]
  - [280, 80, 66]
  - [280, 45, 66]
  - [280, 10, 66]
  - [280, 0, 50]
  - [55, 0, 50]
  - [55, 10, 90]
  - [15, 65, 90]
  - [15, 65, 90]

###
# Fractal
###

escape_block: 131072
escape_limit: 1048576
escape_radius: 16.0

re: -0.5
im: 0.0
re_c: ""
im_c: ""
scale: 1.0
scale_factor: 0.66

perturbation: false
grid_x: 32
grid_y: 32
grid_levels: 2
grid_steps: 2

###
# Image
###

image_directory: "output"
image_name_prefix: ""

image_width: 1024
image_height: 768

###
# Run
###

count: 1
skip: 0

interactive: false
oversample: true
oversample_multiplier: 2