###
# CUDA
###

cuda_groups: 256
cuda_threads: 1024

###
# Colouring
###

colour_method: 2
colour_palette:
  - [0, 0, 0] # Points in set
  - [205, 95, 15]
  - [205, 95, 30]
  - [205, 95, 50]
  - [205, 100, 90]
  - [175, 50, 90]
  - [175, 0, 90]
  - [100, 0, 90]
  - [58, 0, 90]
  - [58, 0, 90]
  - [58, 100, 90]
  - [58, 100, 90]
  - [30, 100, 90]
  - [25, 100, 90]
  - [10, 100, 100]

###
# Fractal
###

escape_block: 65536
escape_limit: 262144
escape_radius: 16.0

re: -0.5
im: 0.0
re_c: ""
im_c: ""
scale: 1.0
scale_factor: 0.5

###
# Image
###

image_directory: "output"
image_name_prefix: ""

image_width: 1024
image_height: 768

###
# Run
###

count: 1
skip: 0

follow_variance: false
random: false
reset: false
trial: true

interactive: false
oversample: false
oversample_multiplier: 2