###
# CUDA
###

cuda_groups: 256
cuda_threads: 1024

###
# Colouring
###

colour_method: 2
colour_palette:
  - [0, 0, 0] # Points in set
  - [205, 95, 15]
  - [205, 95, 30]
  - [205, 95, 50]
  - [205, 100, 100]
  - [175, 50, 100]
  - [175, 0, 100]
  - [100, 0, 100]
  - [58, 0, 100]
  - [58, 0, 100]
  - [58, 100, 100]
  - [58, 100, 100]
  - [30, 100, 100]
  - [25, 100, 100]
  - [20, 75, 100]

###
# Fractal
###

escape_block: 65536
escape_limit: 524288
escape_radius: 16.0

re: -0.5
im: 0.0
re_c: ""
im_c: ""
scale: 1.0
scale_factor: 0.75

perturbation: false
grid_x: 32
grid_y: 32
grid_levels: 2
grid_steps: 2

###
# Image
###

image_directory: "output"
image_name_prefix: ""

image_width: 1024
image_height: 768

###
# Run
###

count: 1
skip: 0

interactive: false
oversample: false
oversample_multiplier: 2